// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type TackleItemType = 'rod' | 'reel' | 'lure' | 'line' | 'hook' | 'other';
export type LocationType = 'pond' | 'lake' | 'river' | 'stream' | 'ocean' | 'other';
export type FriendshipStatus = 'pending' | 'accepted' | 'blocked';

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          state: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name?: string | null;
          avatar_url?: string | null;
          state?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          state?: string | null;
          updated_at?: string;
        };
      };
      tackle_items: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          type: TackleItemType;
          brand: string | null;
          model: string | null;
          description: string | null;
          image_url: string | null;
          source_url: string | null;
          scraped_data: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          type: TackleItemType;
          brand?: string | null;
          model?: string | null;
          description?: string | null;
          image_url?: string | null;
          source_url?: string | null;
          scraped_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          type?: TackleItemType;
          brand?: string | null;
          model?: string | null;
          description?: string | null;
          image_url?: string | null;
          source_url?: string | null;
          scraped_data?: Json | null;
          updated_at?: string;
        };
      };
      fish_species: {
        Row: {
          id: string;
          common_name: string;
          scientific_name: string | null;
          image_url: string | null;
          rarity: number;
          average_weight: number | null;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          common_name: string;
          scientific_name?: string | null;
          image_url?: string | null;
          rarity?: number;
          average_weight?: number | null;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          common_name?: string;
          scientific_name?: string | null;
          image_url?: string | null;
          rarity?: number;
          average_weight?: number | null;
          description?: string | null;
        };
      };
      locations: {
        Row: {
          id: string;
          name: string;
          type: LocationType;
          latitude: number;
          longitude: number;
          state: string;
          fish_species: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: LocationType;
          latitude: number;
          longitude: number;
          state: string;
          fish_species?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: LocationType;
          latitude?: number;
          longitude?: number;
          state?: string;
          fish_species?: string[];
          updated_at?: string;
        };
      };
      catches: {
        Row: {
          id: string;
          user_id: string;
          location_id: string | null;
          fish_species_id: string;
          tackle_item_id: string | null;
          weight: number | null;
          length: number | null;
          photo_url: string | null;
          notes: string | null;
          caught_at: string;
          latitude: number | null;
          longitude: number | null;
          weather_data: Json | null;
          points: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          location_id?: string | null;
          fish_species_id: string;
          tackle_item_id?: string | null;
          weight?: number | null;
          length?: number | null;
          photo_url?: string | null;
          notes?: string | null;
          caught_at: string;
          latitude?: number | null;
          longitude?: number | null;
          weather_data?: Json | null;
          points?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          location_id?: string | null;
          fish_species_id?: string;
          tackle_item_id?: string | null;
          weight?: number | null;
          length?: number | null;
          photo_url?: string | null;
          notes?: string | null;
          caught_at?: string;
          latitude?: number | null;
          longitude?: number | null;
          weather_data?: Json | null;
          points?: number;
        };
      };
      friendships: {
        Row: {
          id: string;
          user_id: string;
          friend_id: string;
          status: FriendshipStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          friend_id: string;
          status?: FriendshipStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          friend_id?: string;
          status?: FriendshipStatus;
          updated_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          catch_id: string;
          user_id: string;
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          catch_id: string;
          user_id: string;
          content: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          catch_id?: string;
          user_id?: string;
          content?: string;
          updated_at?: string;
        };
      };
      leaderboard_cache: {
        Row: {
          user_id: string;
          state: string;
          total_catches: number;
          biggest_fish_weight: number | null;
          biggest_fish_length: number | null;
          total_points: number;
          rank_state: number | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          state: string;
          total_catches?: number;
          biggest_fish_weight?: number | null;
          biggest_fish_length?: number | null;
          total_points?: number;
          rank_state?: number | null;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          state?: string;
          total_catches?: number;
          biggest_fish_weight?: number | null;
          biggest_fish_length?: number | null;
          total_points?: number;
          rank_state?: number | null;
          updated_at?: string;
        };
      };
    };
  };
}
